### ISSUE TITLE
如果采用jekyll会不会更好？

### ISSUE THREAD

**Issue by gaoflow** [Muyangmin/glide-docs-cn#1]
我发现Glide文档使用jekyll来写的，hexo固然非常强大，但jekyll可以更好的做到和源文档保持结构上的一致。Pull Request #2

**Comment by vincgao** [comment]
#2

**Comment by Muyangmin** [comment]
**首先，非常感谢关注这个翻译项目并辛苦做了PR**。

我在最初开始翻译时也注意到Glide官方repo使用的是jekyll，但最终换成了使用Hexo，主要是基于以下几点考虑：
1. 翻译项目最重要的是内容呈现，即通常想让大家看到的是*最终的*页面，而不是到项目repo来看目录结构。从这个角度来看，使用 `Hexo` 或是 `Jekyll` 理论上是可以对用户透明的，也不是一定要和原repo保持结构一致。
2. Jekyll 使用 Ruby 环境，而 `Hexo` 依赖于 Node.js。一方面，Ruby在 Windows上的支持一直都不是很好，虽然有 [RubyInstaller](https://rubyinstaller.org/)，但终究不是很方便。而 Node.js 不仅在Windows上能很好兼容，在 `React Native` 相对流行的当下，Android开发者对Node环境应该比Ruby环境要熟悉一些。
3. 虽然我们可以使用`Travis CI`自动部署，但是我认为在提交正式的翻译之前都应当做一次本地预览。`Hexo`这方面似乎也更有优势。

另外，我在翻译过程中发现，由于托管站点的不同， 即使我们使用Jekyll，也没有办法做到完全不修改链接。基于上述第1点考虑，我觉得暂时没有必要重新切回Jekyll。

我看了你的 PR #2 ，看得出来确实做了大量工作，再次向您表示感谢。

以上观点欢迎讨论。

**Comment by gaoflow** [comment]
对于您所提出的几点观点回复如下：

1. 您说的没错，中文文档目的是呈现。Hexo or Jekyll对用户是无感知的。但采用Jekyll的好处包括：
- 可以做到像素级clone原英文文档。
- 采用Jekyll只需要负责维护Markdown文章内容，之后原文档对documentation的layout做出的任何改动均可不用关心。

2. 目前Jekyll和Hexo均支持Windows，Jekyll和Hexo无非都是网页模板，能够运行起来即可，不需要过多关心。参与文档翻译掌握Markdown即可。

3. 我不太清楚您所说Hexo在本地预览所有的优势具体是指哪些方面。在我看来运行`hexo s`和`jekyll s`并无区别，均十分方便。

如果采用Hexo来维护，带来的一个潜在影响是会增加维护成本。就像您所提的这个[issue](https://github.com/bumptech/glide/issues/2377)。文档内的链接都是相对路径，并不会因为托管站点的不同而导致链接失效。如果采用Jekyll部署，就不需要考虑类似迁移过程中可能出现到的不兼容现象。

Hexo 和 Jekyll 均是十分优秀、强大的框架。如果我们是做中文文档翻译和维护工作，借助已有资源，把重点放在文章本身，是不是更能够专注和高效呢 ：）

另外[Fresco的文档维护项目](https://github.com/liaohuqiu/fresco-docs-cn)也可作为本项目的一个参考

**Comment by Muyangmin** [comment]
谢谢指教，我需要时间再研究一下 Jekyll 再决定是否接受PR。

**另外我觉得是不是可以在中文repo里把javadocs路径下 3.8.0以前的文件删了，目前文档中已经不会引用这些页面了（以后也不应该会~）**

**Comment by gaoflow** [comment]
指教不敢当。Jekyll的学习成本跟Hexo类似，很多UI方面的事情Glide的维护者已经帮我们做好了，在此基础之上做一些中文优化即可。当然用Hexo也可以做 ：）

对于javadocs路径下 3.8.0以前的文件，我的看法是，内容尽量和原文档保持一致，我们只做搬运和翻译工作，内容上尊重原作者，不做过多修改。留不留无伤大雅哈哈~

**Comment by Muyangmin** [comment]
@vincgao 我在本地实验了一下，看上去很不错，但可能还有一个问题需要在合并PR之后处理。

我注意到你在Jekyll项目的`_config.yml`文件设置的`baseurl`是 `glide`。
```YAML
# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: '/glide'
```
但是根据 GitHub的 [Pages域名规则](https://help.github.com/articles/user-organization-and-project-pages/)，`glide-docs-cn`项目的地址只能是`glide-docs-cn`，而不能设置为 `glide`（强行设置会在访问时遇到404错误）。这个问题会影响到javadoc链接的访问。

举个栗子，现在文档中有两种访问javadoc链接的方式：
[javadocs.md](https://raw.githubusercontent.com/bumptech/glide/gh-pages/_posts/2015-05-17-javadocs.md)
```Text
[1]:{{ site.baseurl }}{% link /javadocs/410/index.html %}
```
[download-setup.md](https://raw.githubusercontent.com/bumptech/glide/gh-pages/_posts/2015-05-15-download-setup.md)
```Text
[6]: {{ site.url }}/glide/doc/generatedapi.html#kotlin
```

Sjudd和BumpTech的文档恰好托管在 glide 仓库下，因此两种方式都可以访问。但当我们在把这一份代码托管到 **不同名的** 任何一个repo下，第二种链接就悲剧了……**404**

从技术上讲，我们可以fork一份glide，甚至直接建立一个空的repo叫做`glide`来解决这个问题，但很显然这影响了仓库名原有的语义，因此我觉得绝对不能这么做。

所以我认为应该需要将文档中的第二种访问方式改为第一种方式访问。至于由此带来的中英文档不同步的问题，我可以给glide官方repo再开一个PR。

你看这个结论是否有问题？如果没有的话周末就可以做这个事情了:stuck_out_tongue_closed_eyes:

**Comment by gaoflow** [comment]
同意你的观点。目前看来`{{ site.url }}/glide` 与 `{{ site.baseurl }}`作用等价。

提交PR的事情那就你来搞啦。如果你同意改用Jekyll的话，我会周末在家继续做两件事情：
1. 早上做在迁移时，发现部分内容已有更新，我会帮忙校对一遍目前文档的状态
2. 帮忙校对翻译（正好也是熟悉Glide v4最好的机会）

我比较手生，之前没有做过类似的事情，任何问题欢迎批评指正。期间若有任何好想法我会随时提出，希望能把Glide新的文档维护好，帮助到更多的中国开发者！

**Comment by Muyangmin** [comment]
我在Windows cmd环境和 Cygwin环境都折腾了一遍Jekyll，现在应该可以放心合并代码了 :joy:

**Comment by Muyangmin** [comment]
@vincgao 代码已合并并处理了site.url  ([commit](https://github.com/Muyangmin/glide-docs-cn/commit/a79c5798ac318e96ad9192362ca6d300201056f5),  bumptech/glide#2400 )，现在站点基本可用了。请放心校对，随时欢迎PR :stuck_out_tongue_closed_eyes:
