### ISSUE TITLE
Glide版本更新，有些方法被去除了

### ISSUE THREAD

**Issue by liweijieok** [Muyangmin/glide-docs-cn#24]
#### 文档滞后:  
目前Glide版本最小是4.7.1了，发现有些方法被去除了，比placeholder()等。

**Comment by Muyangmin** [comment]
@liweijieok 抱歉，~~因最近个人工作和生活出现了一些波动导致~~确实一段时间内没有很好地跟进更新文档。我会尽快更新文档，谢谢提醒。

**Comment by liweijieok** [comment]
不会，大佬辛苦了。慢慢来不急。
