### ISSUE TITLE
不更新了吗.已经4.11.0了

### ISSUE THREAD

**Issue by rowenl** [Muyangmin/glide-docs-cn#30]

**Comment by Muyangmin** [comment]
抱歉最近几个月太忙了没顾上，近期尽量抽空做一次校对。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Wenlong&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月3日(星期五) 下午5:50
收件人:&nbsp;&quot;Muyangmin/glide-docs-cn&quot;<glide-docs-cn@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Muyangmin/glide-docs-cn] 不更新了吗.已经4.11.0了 (#30)

**Comment by rowenl** [comment]
哈哈.真没想到是你在维护.认识我吗

**Comment by Muyangmin** [comment]
从名字猜……是认识的( ͡° ͜ʖ ͡°)✧------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Wenlong&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月3日(星期五) 晚上7:42
收件人:&nbsp;&quot;Muyangmin/glide-docs-cn&quot;<glide-docs-cn@noreply.github.com&gt;;
抄送:&nbsp;&quot;Muyangmin&quot;<muyangmin@foxmail.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Muyangmin/glide-docs-cn] 不更新了吗.已经4.11.0了 (#30)
