### ISSUE TITLE
名词翻译讨论

### ISSUE THREAD

**Issue by gaoflow** [Muyangmin/glide-docs-cn#5]
关于 Generated API，我认为翻译成“生成的API”不够达到“信·达·雅”的标准，开发者看到“生成的API”很难能够理解其中含义。是否可以暂时先保留Generated API，不做翻译。或者需要一个更传神的翻译

**Comment by Muyangmin** [comment]
实际上`Generated API` 一直是翻译时很纠结的问题，来回改了很多遍:disappointed_relieved: 

我把#4 合并了，但是我觉得我们是否需要开一个长期的issue，把这种大家都觉得不好翻译的挂出来，供更多人讨论一下？

**Comment by gaoflow** [comment]
是的，有对名词做讨论的，在本issue下留言即可

**Comment by 123ufo** [comment]
顺便把Greendao也翻译了.加油
