### ISSUE TITLE
翻译文档同步计划

### ISSUE THREAD

**Issue by Muyangmin** [Muyangmin/glide-docs-cn#6]
因官方文档仓库 [glide](https://github.com/bumptech/glide/tree/gh-pages) 经常修改文档内容，很容易造成中文版与英文版不同步的情况，故打算使用脚本自动维护文档的一致性。

具体计划：
1. 对源地址的 `_posts` 文件夹完全拷贝一份，放置在本仓库的 `mirror` 文件夹下；
2. 定期调用 [GitHub Contents API](https://developer.github.com/v3/repos/contents/#get-contents)，遍历对比源地址和本仓库的镜像文档 `sha` 值；
3. 如果发现有 `sha` 值不一致的文件，或源地址增删了文件，则使用机器人账户在本仓库发起一个 [`Issue`](https://github.com/Muyangmin/glide-docs-cn/issues) 并等待维护者 review。
4. *Optional* 如果文档完全一致，则修改本项目下的 `footer` 文件，注明最后同步日期。

**Comment by WangXin008** [comment]
> 因官方文档仓库 [glide](https://github.com/bumptech/glide/tree/gh-pages) 经常修改文档内容，很容易造成中文版与英文版不同步的情况，故打算使用脚本自动维护文档的一致性。
> 
> 具体计划：
> 
> 1. 对源地址的 `_posts` 文件夹完全拷贝一份，放置在本仓库的 `mirror` 文件夹下；
> 2. 定期调用 [GitHub Contents API](https://developer.github.com/v3/repos/contents/#get-contents)，遍历对比源地址和本仓库的镜像文档 `sha` 值；
> 3. 如果发现有 `sha` 值不一致的文件，或源地址增删了文件，则使用机器人账户在本仓库发起一个 [`Issue`](https://github.com/Muyangmin/glide-docs-cn/issues) 并等待维护者 review。
> 4. _Optional_ 如果文档完全一致，则修改本项目下的 `footer` 文件，注明最后同步日期。

有写好的脚本分享吗？遇到了同样的问题~

**Comment by superen7527** [comment]
好像很久没跟进翻译了。
